---
title: "Thesis Chapter 2 version 0.1"
author: "Dr Greig Russell"
date: "6/28/2020"
output:
  pdf_document: 
    toc: true
    toc_depth: 3
    citation_package: natbib
    number_sections: yes
link_citations: yes
bibliography: Reference.bib
header - includes:
  - \usepackage(amsmath)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

George Boole (1815 - 1864) was born in Lincoln and died in Cork. He was a self-taught mathematician and educationalist, who was too poor to attend Cambridge (Chap.4, @machale2014life) yet became the foundation professor of mathematics at Cork and a Fellow of the Royal Society (Chap.5, @machale2014life). His work has influenced much of what has followed particularly with regards to Computer Science and logic. He first used the “Universe of Discourse” (p. 30 @boole1854investigation) and the abstract variable type of logical variables is called a Boolean in some computer languages like Pascal (@hayward1986compared).

Boole was no means some random savant, emerging from the wilderness to transform academia without access to prior learning. Although he is sometimes portrayed as such, he was very much engaged in the spirit of the age (Chap. 1, @machale2014life). @machale2014life outlines how that Boole’s father, John, was indeed a cobbler, whose business was challenged, which had a significant constraining influence on Boole’s life choices.  The reason for this state of impoverished affairs was that John lacked interest in being a Cobbler. Preferring instead to make optical instruments, and John was a life long learner in science, literature and mathematics. Indeed, even when famous George’s mother regarded his father as being more gifted despite George’s fame (@machale2014life).

As a child, George was fascinated with mathematics and other “abstract” subjects. His father taught George the joy of practical science through the family telescope and his father’s love of astronomy. However, George had a broad reach of interests including the humanities, arts and sports but was by nature a quiet, retiring, man (@machale2014life). It was George’s interests in the humanities that first drew his brilliance to public attention, although his father’s financial situation limited his choices, George attended a period of secondary education and supplemented this by learning several European languages. This enabled George to stay abreast of academic learnings in Europe (@machale2014life).

This state of relative impoverishment meant as George had to buy all his own books, he focused on mathematics as being better value for money. Admirers also gave him access to similar such as Lacroix’s *Differential and Integral Calculus* or Newton’s *Principia* (@nahin2017logician). Being self-taught, meant he was self-reliant and needed to develop a rigour to his study as he lacked teachers to ease his academic journey (@machale2014life).

By 1844, Boole earned a Royal Medal for his paper on the “On a general method on analysis” (@boole1844viii) and by 1849, despite not having any degree, Boole, was appointed the foundation professor in mathematics at Queen’s College in Cork, Ireland (@nahin2017logician). Boole would reside in Cork until his death but married in 1850. He had five daughters, all of who were equally talented in a plethora of subjects in their own right(@machale2014life).

In 1854, Boole published the key work of relevance to this study, “An Investigation Of The Laws Of Thought, On Which Are Founded The Mathematical Theories Of Logic And Probabilities” (@boole1854investigation).

# Key Idea

@boole1854investigation seeks to bridge the gap between words and symbols, built on the preface “that Language is an instrument of human reason (p. 17)” although admitting that some have argued to reason without such an assumption.

The formulation rules of Boole’s algebra are;

A language consists of words which are signs or symbols, where a sign is admittedly arbitrary in its definition, within a given context and other associated signs.
Such an arbitrary definition may be contextual but within that context, it is also consistent within that context.
Such conceptual signs are represented by symbols as x, y…
+, -, * are signs of operation by which conceptual signs are combined or similar...
= is the sign for identity.
A combination of signs like “xy” is taken as the combination of x ^ y.
Given 6, then “xy = yx”.

Then Boole’s key insight can be developed;

\begin{equation}
 xy = x
\end{equation}

Which is taken to mean for a combination object “white horned sheep” expresses a class of objects like all sheep. Then consider the case where;

\begin{equation}
 xx = x
\end{equation}

Which is the case where x is of the same class as y. Hence;

\begin{equation}
 x^2 = x
\end{equation}

Which is only true if x = 0 or x = 1.


# Boole's Ontology

## An Investigation of the Laws of Thought
For @boole1854investigation his book “An investigation of the laws of thought: on which are founded the mathematical theories of logic and probabilities” was his seminal work. Clearly it has given inspiration to others in fields like Computer Science, Number theory and Logic. As will be discussed later, much of what is discussed in respect of Boole's work, is confabulated with subsequent scholarship that Boole did not formally discussed but was an incidental implication. Boole was clear his focus was on logic and reasoning;

*“1. The design of the following treatise is to investigate the fundamental laws of those operations of the mind by which reasoning is performed; to give expression to them in the symbolical language of a Calculus, and upon this foundation to establish the science of Logic and construct its method; to make that method itself the basis of a general method for the application of the mathematical doctrine of Probabilities; and, finally, to collect from the various elements of truth brought to view in the course of these inquiries some probable intimations concerning the nature and constitution of the human mind. ”* ( @boole1854investigation, paragraph 1.1).

For Boole, this was an evolution from his previous work “The Mathematical Analysis of Logic” (@boole1847mathematical), rather “An Investigation of the Laws of Thoughts” was 

*“Its earlier portion is indeed devoted to the same object, and it begins by establishing the same system of fundamental laws, but its methods are more general, and its range of applications far wider. It exhibits the results, matured by some years of study and reflection, of a principle of investigation relating to the intellectual operations, the previous exposition of which was written within a few weeks after its idea had been conceived...”* (@boole1854investigation, p. iii).

Boole also linked his work back to Whately’s earlier “Elements of Logic” (@whately1826elements). @Neumann2018whately described Whately’s work as introducing Aristotelian logic to the Victorian public. By the beginning of the 17th century, Oxford University was the last remaining stronghold of Aristotle’s logic, but it was under attack from all sides largely seen as useless, fit only to torture undergraduates (@Neumann2018whately). 

To counter this perception, @whately1826elements published a widely popular defence of Aristotle that ran to nine editions and introduced logic to the Victoria public. “Elements of logic” describe the development of logic from the pre-socratic greek philosophers to Locke. For @whately1826elements, logic was both a science and an art. It was science when it was applied to the “theory of reasoning” and art when it was the application of knowledge was into practice (@whately1826elements, p. 1).

In “Of the Operations of the Mind and of Terms”, Whately starts to consider what Boole would expand upon (@whately1826elements, p. 251). Namely, the three states within the mind. The first is “Simple-apprehension” is the sense perception of an object. Such apprehension can be either “incomplex” (or a single object like a horse) or complex (or conjunction of simple objects to make a complex concept like a man on a horse). Such objects can be compared or judged to see if they agree or not. While reasoning, for Whately, is proceeding from initial judgements to subsequent judgements based on the results of earlier comparisons or new apprehensions (@whately1826elements, pp. 251-252).  This cyclical learning from earlier information or judgements is reminiscent of what will become “Bayes theorem” where new observations update prior probabilities. Boole will build upon the Whately’s stance that information was the sense derived cognitive representation of an external object on which the mind acted.

Boole appears to be caught in a quandary about the apparent nature of external reality and the internal objects of cognition.

*” The general laws of Nature are not, for the most part, immediate objects of perception. They are either inductive inferences from a large body of facts, the common truth in which they express, or, in their origin at least, physical hypotheses of a causal nature serving to explain phenomena with undeviating precision, and to enable us to predict new combinations of them. They are in all cases, and in the strictest sense of the term, probable conclusions, approaching, indeed, ever and ever nearer to certainty, as they receive more and more of the confirmation of experience. But of the character of probability, in the strict and proper sense of that term, they are never wholly divested. On the other hand, the knowledge of the laws of the mind does not require as its basis any extensive collection of observations.”* (@boole1854investigation, para 1.4).

While working from the basis that;

*” Let the assumption be granted, that a science of the intellectual powers is possible, and let us for a moment consider how the knowledge of it is to be obtained.“* (@boole1854investigation, para 1.3).

And that;

*” Like all other sciences, that of the intellectual operations must primarily rest upon observation,{the subject of such observation being the very operations and processes of which we desire to determine the laws.“* (@boole1854investigation, para 1.4).

A problem he seeks to resolve through both the adoption and rejection of a dualism;

*” Now that truth is made manifest in all its generality by reflection upon a single instance of its application. And this is both an evidence that the particular principle or formula in question is founded upon some general law or laws of the mind, and an illustration of the doctrine that the perception of such general truths is not derived from an induction from many instances, but is involved in the clear apprehension of a single instance. In connexion with this truth is seen the not less important one that our knowledge of the laws upon which the science of the intellectual powers rests, whatever may be its extent or its deficiency, is not probable knowledge. For we not only see in the particular example the general truth, but we see it also as a certain truth,{a truth, our confidence in which will not continue to increase with increasing experience of its practical verifications. “*, (@boole1854investigation, para 1.5).

Here Boole argues for the duality of the cognitive objects being based on the induction from repeated observation and on the clear understanding of a single instance from which a “certain” truth (almost akin to a mathematical proof of a given law) will be derived. As the former only gives a probable or general truth, Boole’s focus is on later “certain” truths as the basis for the Science of Logic.

*” 5. But if the general truths of Logic are of such a nature that when presented to the mind they at once command assent, wherein consists the difficulty of constructing the Science of Logic? Not, it may be answered, in collecting the materials of knowledge, but in discriminating their nature, and determining their mutual place and relation.“*, (@boole1854investigation, para 1.5).

*” Let us define as fundamental those laws and principles from which all other general truths of science may be deduced, and into which they may all be again resolved. Shall we then err in regarding that as the true science of Logic which, laying down certain elementary laws, confirmed by the very testimony of the mind, permits us thence to deduce, by uniform processes, the entire chain of its secondary consequences, and furnishes, for its practical applications, methods of perfect generality? Let it be considered whether in any science, viewed either as a system of truth or as the foundation of a practical art, there can properly be any other test of the completeness and the fundamental character of its laws, than the completeness of its system of derived truths, and the generality of the methods which it serves to establish.“*, (@boole1854investigation, para 1.5).

Having established the primacy of abstractions as the objects of cognition, Boole turns to the central construct of his work;

*” It is designed, in the next place, to give expression in this treatise to the fundamental laws of reasoning in the symbolical language of a Calculus. Upon this head it will suffice to say, that those laws are such as to suggest this mode of expression, and to give to it a peculiar and exclusive fitness for the ends in view. There is not only a close analogy between the operations of the mind in general reasoning and its operations in the particular science of Algebra, but there is to a considerable extent an exact agreement in the laws by which the two classes of operations are conducted. Of course the laws must in both cases be determined independently; any formal agreement between them can only be established a posteriori by actual comparison“*, (@boole1854investigation, para1.6).

Before acknowledging that there must be some form of parity between the nature and actions of external objects and internal abstractions;

*” Logic is conversant with two kinds of relations,{relations among things, and relations among facts. But as facts are expressed by propositions, the latter species of relation may, at least for the purposes of Logic, be resolved into a relation among propositions. The assertion that the fact or event A is an invariable consequent of the fact or event B may, to this extent at least, be regarded as equivalent to the assertion, that the truth of the proposition arming the occurrence of the event B always implies the truth of the proposition arming the occurrence of the event A.“* (@boole1854investigation, para 1.7).

To give structure to his calculus Boole argues that;

*” Of the former kind of relations we have an example in the proposition “All men are mortal;" of the latter kind in the proposition “If the sun is totally eclipsed, the stars will become visible." The one expresses a relation between “men" and “mortal beings," the other between the elementary propositions “The sun is totally eclipsed;" “The stars will become visible." … Proceeding from this definition, we may then say that the premises of any logical argument express given relations among certain elements, and that the conclusion must express an implied relation among those elements, or among a part of them, i.e. a relation implied by or inferentially involved in the premises.  “* (@boole1854investigation, para 1.7).

A position which is analogous to his description of the relations between general truths based on repeated observations and their probable predictive power as discussed earlier.

**This assumption of the primacy of determinism based on abstract reasoning over probablmism based on observation as the basis for the universe will have far reaching effects, given the role of Boole's influence in information and computer science.**

Boole’s ontology continued
Boole returns to the dualism between the abstract and the probabilistic objects of cognition.  As before, these entities remain distinct but exist in parallel so allowing his calculus to be applied to both;

*” The general doctrine and method of Logic above explained form also the basis of a theory and corresponding method of Probabilities. Accordingly, the development of such a theory and method, upon the above principles, will constitute a distinct object of the present treatise.*

…

*Speaking technically, we must be able to express the event whose probability is sought, as a function of the events whose probabilities are given. Now this explicit determination belongs in all instances to the department of Logic. Probability, however, in its mathematical acceptation, admits of numerical measurement. Hence the subject of Probabilities belongs equally to the science of Number and to that of Logic.“* (@boole1854investigation, para 1.12)

Boole uses the term data with respect to understanding probability as follows;

*” Considered with reference to the data and the quaesitum, that type may be described as follows:*

*1st. The data are the probabilities of one or more given events, each probability being either that of the absolute fulfilment of the event to which it relates, or the probability of its fulfilment under given supposed conditions. *

*2ndly. The quaesitum, or object sought, is the probability of the fulfilment, absolutely or conditionally, of some other event differing in expression from those in the data, but more or less involving the same elements. As concerns the data, they are either causally given,- as when the probability of a particular throw of a die is deduced from a knowledge of the constitution of the piece - or they are derived from observation of repeated instances of the success or failure of events. In the latter case the probability of an event may be de ned as the limit toward which the ratio of the favourable to the whole number of observed cases approaches (the uniformity of nature being presupposed) as the observations are indefinitely continued.“*, (@boole1854investigation, para 1.13).

Suggesting that data is numbers driven by the laws of probability and related to the observed external world. As opposed to information which is the single abstract entity from which a proven fundamental law can rest. What is not clear from Boole’s work is the relationship between data and information, or more simply if the latter is not derived from sense data then how it is formed? If it is formed from sense data, then why is it exempt from the laws of probability that underpin Boole’s experienced universe?

Boole argues that external events are simple or compound;

*” Now one general problem, which the existing theory of Probabilities enables us to solve, is the following, viz.:-Given the probabilities of any simple events: required the probability of a given compound event, i.e. of an event compounded in a given manner out of the given simple events.“*, (@boole1854investigation, para 1.14).

Where compound events are often linked by either simple association or by “cause and effect”.

*” The problem can also be solved when the compound event, whose probability is required, is subjected to given conditions, i.e. to conditions dependent also in a given manner on the given simple events. Beside this general problem, there exist also particular problems of which the principle of solution is known. Various questions relating to causes and effects can be solved by known methods under the particular hypothesis that the causes are mutually exclusive, but apparently not otherwise.“* (@boole1854investigation, para 1.14).

Although he does not expand on the differences between a simple association and specific causation for the existence of compound events. Boole states that even events with an apparent cause to the observed effects are still only secondary objects as they can not support general truths like an abstract object.

*” All sciences consist of general truths, but of those truths some only are primary and fundamental, others are secondary and derived. The laws of elliptic motion, discovered by Kepler, are general truths in astronomy, but they are not its fundamental truths.“* (@boole1854investigation, para 1.5)

Given Boole’s claim that;

*” In the first place it is always possible, by the preliminary method of the Calculus of Logic, to express the event whose probability is sought as a logical function of the events whose probabilities are given.“*, (@boole1854investigation, para 1.15)

It would be tempting to suggest that Boole’s resolution of the duality between the abstract and the probabilistic is that both can be objects within his logical calculus. So although they have different concepts, and one has primacy over the other, both are still objects of the laws of thought.

## Law of duality
Boole’s proposed his law of duality;

\begin{equation}
x(1-x) = 0
\end{equation}

*" Hence x(1-x) will represent the class whose members are at once "men," and "not men," and the equation (1) thus express the principle, that a class whose members are at the same time men and not men does not exist. In other words, that it is impossible for the same individual to be at the same time a man and not a man.  Now let the meaning of the symbol x be extended from the representing of "men," to that of any class of beings characterized by the possession of any quality whatever; and the equation (1) will then express that it is impossible for a being to possess a quality and not to possess that quality at the same time...Thus it is a consequence of the fact that the fundamental equation of thought is of the second degree, that we perform the operation of analysis and classification, by division into pairs of opposites, or, as it is technically said, by dichotomy.'* (@boole1854investigation, para 3.15)

Where Boole means that an equation of the second degree is one where;

\begin(equation}
x^2 = x
\end{equation}

And a third order equation would be to the third power. Boole then goes onto to define the above as the law of duality;

*"The law of thought expressed by the equation (1) will, for reasons which are made apparent by the above discussion, be occasionally referred to as the "law of duality."* (@boole1854investigation, para 3.16)

Boole makes extensive use of this law of duality is the algebraic resolution of the propositions. 

*“We may arm, that in this peculiar system, the problem of elimination is resolvable under all circumstances alike. This is a consequence of that remarkable law of duality to which the symbols of Logic are subject. To the equations furnished by the premises given, there is added another equation or system of equations drawn from the fundamental laws of thought itself, and supplying the necessary means for the solution of the problem in question. Of the many consequences which flow from the law of duality, this is perhaps the most deserving of attention. "* (@boole1854investigation, para 7.2)

Thus for Boole, the dualism between external realism and internal cognitive objects is not in the sense of Cartesian dualism, rather it is the dualism of opposites. 

*“The famous comparison of the universe to a lyre or a bow, its “recurrent harmony" being the product of opposite states of tension, betrays the same origin. In the system of Pythagoras, which seems to have been a combination of dualism with other elements derived from the study of numbers, and of their relations, ten fundamental antitheses are recognised:  finite and infinite, even and odd, unity and multitude, right and left, male and female, rest and motion, straight and curved, light and darkness, good and evil, the square and the oblong ”*  (@boole1854investigation, para 12.7)

Leading to him adopting a position more akin to Socrate’s Cave and the theory of forms;

*“The unity of all real being, its identity with truth and goodness considered as to their essence; the illusion, the pro-found unreality, of all merely phenomenal existence; such were the views,|such the dispositions of thought, which it chiefly tended to foster. *” (@boole1854investigation, para 12.7)

And

*"Were this correspondence between the forms of thought and the actual constitution of Nature proved to exist, whatsoever connexion or relation it might be supposed to establish between the two systems, it would in no degree affect the question of their mutual independence."* (@boole1854investigation, para 12.8)

So that

*"We have no warrant for resolving these into mere forms of the understanding, though they unquestionably determine the present sphere of our knowledge. And, to speak more generally, there is no warrant for the extremely subjective tendency of much modern speculation. Whenever, in the view of the intellect, different hypotheses are equally consistent with an observed fact, the instinctive testimony of consciousness as to their relative value must be allowed to possess authority. ”* (@boole1854investigation, para 12.8)

For Boole then, the cognitive objectives that were manipulated by his algebra were Socratic rather than Cartesian in nature, where the cognitive object was the pure form on which the purity of mathematical thought could be applied.


\newpage