---
title: "Thesis Chapter 2"
author: "Version 0.2"
date: "6/28/2020"
output:
  pdf_document: 
    toc: true
    toc_depth: 3
    citation_package: natbib
    number_sections: yes
link_citations: yes
bibliography: Reference.bib
header - includes:
  - \usepackage(amsmath)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
This chapter will outline George Boole’s central role in the evolution of Information Science in general and the ontology of information of information in particular. George Boole’s thesis contained two key ideas. That idealized internal mental objects can be represented as a series of abstraction propositions on which algebraic manipulations can be performed to reveal the laws of reason that underpin human thought.

As will be described  George Boole saw his thinking as being a direct descendant from Aristotle’s logic. By the early 19th century, the teaching of Aristotle’s logic was on the wan and only taught at Christ College, Oxford. It was revived through the efforts of Archbishop Whatley, who published a popular text the “Elements of logic”. Aside from saving Aristotle’s teaching, Whatley also considered the nature of the relationship between cognitive objects and their external sensory counterparts.

Boole expanded on this work, and as will be discussed later, adopted a position of Platonic dualism. Where internal objects are pure and by definition absolute perfection. The external sensory objects are shadows of this pure form, that are often distorted so can only be described by the use of statistics to manage the variability.

This thesis will argue that this platonic dualism got left behind as an unspoken assumption with its implied determinism as the basis for reality in the subsequent development of computational logic, the philosophy of information and the subsequent development of many computer programming paradigms and their subsequent computer languages.

Boole’s algebra is how he proposed that the laws of reason considered both objective pure reality and external subjective reality. It enables insights and the truth to be determined by mathematical reductionism. Key to this was algebra was his “law of duality” that if;

\begin{equation}
x^ = x
\end{equation}

Then it is only true if X = 0 or X = 1. Although now universally adopted, it was Boole who allocated “0” to be null or false, and “1” to be truth or existence. He then used this approach to attract values to the propositions that made up his internal pure objects and went onto to show it could also provide the basis for the approach to probability theory and external objects.

Boole goes on to describe the nature of these propositions, which he divides into primary and secondary. Throughout the text, his thinking on the nature and differences between such evolve. The conclusion advanced in this thesis is that in the end, Boole associated the specific attributes of a primary mental object to its primary propositions and whether these primary attributes exist or not in time and space to secondary attributes. Causation is key to Boole's intreptation of probability and Boole adopts a position sympathetic to Hume's regularity as the basis for causation.

# George Boole - a brief biography
George Boole (1815 - 1864) was born in Lincoln and died in Cork. He was a self-taught mathematician and educationalist, who was too poor to attend Cambridge (@machale2014life, Chap. 4) yet became the foundation professor of mathematics at Cork and a Fellow of the Royal Society (@machale2014life, Chap. 5). His work has influenced much of what has followed particularly with regards to Computer Science and logic. He first used the “Universe of Discourse” (@boole1854investigation, p. 30) and the abstract variable type of logical variables is called a Boolean in some computer languages like Pascal (@hayward1986compared).

Boole was no means some random savant, emerging from the wilderness to transform academia without access to prior learning. Although he is sometimes portrayed as such, he was very much engaged in the spirit of the age (@machale2014life, Chap. 1). @machale2014life goes on to outline how that Boole’s father, John, was indeed a cobbler, whose business was financially challenged, which had a significant constraining influence on Boole’s life choices as the mythology outlines.  The reason for this state of impoverished fiscal affairs was that John lacked interest in being a Cobbler. John prefered instead to make optical instruments, and he was a life long learner in science, literature and mathematics. Indeed, even when her son was famous, George’s mother regarded her husband as being more gifted than her son (@machale2014life).

As a child, George was fascinated with mathematics and other “abstract” subjects. His father taught George the joy of practical science through the family telescope and his father’s love of astronomy. However, George had a broad reach of interests including the humanities, arts and sports but was by nature a quiet, retiring, man (@machale2014life). It was George’s interests in the humanities that first drew his brilliance to public attention, although his father’s financial situation limited his choices, George attended a period of secondary education and supplemented this by learning several European languages. This enabled George to stay abreast of academic learnings in Europe (@machale2014life).

This state of relative impoverishment meant as George had to buy all his own books, he focused on mathematics as being better value for money. Admirers also gave him access to similar such as Lacroix’s *Differential and Integral Calculus* or Newton’s *Principia* (@nahin2017logician). Being self-taught, meant he was self-reliant and needed to develop a rigour to his study as he lacked teachers to ease his academic journey (@machale2014life).

By 1844, Boole earned a Royal Medal for his paper on the “On a general method on analysis” (@boole1844viii) and by 1849, despite not having any degree, Boole, was appointed the foundation professor in mathematics at Queen’s College in Cork, Ireland (@nahin2017logician). Boole would reside in Cork until his death but married in 1850. He had five daughters, all of who were equally talented in a plethora of subjects in their own right(@machale2014life).

In 1854, Boole published the key work of relevance to this study, “An Investigation Of The Laws Of Thought, On Which Are Founded The Mathematical Theories Of Logic And Probabilities” (@boole1854investigation).

# An investigation of the laws of thought

For @boole1854investigation his book “An investigation of the laws of thought: on which are founded the mathematical theories of logic and probabilities” was his seminal work. Clearly it has given inspiration to others in fields like Computer Science, Number theory and Logic. As will be discussed later, much of what is discussed in respect of Boole's work, is confabulated with subsequent scholarship that Boole did not formally discussed but was an incidental implication. Boole was clear his focus was on logic and reasoning;

*“1. The design of the following treatise is to investigate the fundamental laws of those operations of the mind by which reasoning is performed; to give expression to them in the symbolical language of a Calculus, and upon this foundation to establish the science of Logic and construct its method; to make that method itself the basis of a general method for the application of the mathematical doctrine of Probabilities; and, finally, to collect from the various elements of truth brought to view in the course of these inquiries some probable intimations concerning the nature and constitution of the human mind. ”* ( @boole1854investigation, paragraph 1.1).

For Boole, this was an evolution from his previous work “The Mathematical Analysis of Logic” (@boole1847mathematical), rather “An Investigation of the Laws of Thoughts” was 

*“Its earlier portion is indeed devoted to the same object, and it begins by establishing the same system of fundamental laws, but its methods are more general, and its range of applications far wider. It exhibits the results, matured by some years of study and reflection, of a principle of investigation relating to the intellectual operations, the previous exposition of which was written within a few weeks after its idea had been conceived...”* (@boole1854investigation, p. iii).

Boole also linked his work back to Whately’s earlier “Elements of Logic” (@whately1826elements). @Neumann2018whately described Whately’s work as introducing Aristotelian logic to the Victorian public. By the beginning of the 17th century, Oxford University was the last remaining stronghold of Aristotle’s logic, but it was under attack from all sides largely seen as useless, fit only to torture undergraduates (@Neumann2018whately). 

To counter this perception, @whately1826elements published a widely popular defence of Aristotle that ran to nine editions and introduced logic to the Victoria public. “Elements of logic” describe the development of logic from the pre-socratic greek philosophers to Locke. For @whately1826elements, logic was both a science and an art. It was science when it was applied to the “theory of reasoning” and art when it was the application of knowledge was into practice (@whately1826elements, p. 1).

In “Of the Operations of the Mind and of Terms”, Whately starts to consider what Boole would expand upon (@whately1826elements, p. 251). Namely, the three states within the mind. The first is “Simple-apprehension” is the sense perception of an object. Such apprehension can be either “incomplex” (or a single object like a horse) or complex (or conjunction of simple objects to make a complex concept like a man on a horse). Such objects can be compared or judged to see if they agree or not. While reasoning, for Whately, is proceeding from initial judgements to subsequent judgements based on the results of earlier comparisons or new apprehensions (@whately1826elements, pp. 251-252).  This cyclical learning from earlier information or judgements is reminiscent of what will become “Bayes theorem” where new observations update prior probabilities. Boole will build upon the Whately’s stance that information was the sense derived cognitive representation of an external object on which the mind acted.

## Boole's ontology
### Boole's dualism

Boole appears to be caught in a quandary about the apparent nature of external reality and the internal objects of cognition.

*” The general laws of Nature are not, for the most part, immediate objects of perception. They are either inductive inferences from a large body of facts, the common truth in which they express, or, in their origin at least, physical hypotheses of a causal nature serving to explain phenomena with undeviating precision, and to enable us to predict new combinations of them. They are in all cases, and in the strictest sense of the term, probable conclusions, approaching, indeed, ever and ever nearer to certainty, as they receive more and more of the confirmation of experience. But of the character of probability, in the strict and proper sense of that term, they are never wholly divested. On the other hand, the knowledge of the laws of the mind does not require as its basis any extensive collection of observations.”* (@boole1854investigation, para 1.4).

While working from the basis that;

*” Let the assumption be granted, that a science of the intellectual powers is possible, and let us for a moment consider how the knowledge of it is to be obtained.“* (@boole1854investigation, para 1.3).

And that;

*” Like all other sciences, that of the intellectual operations must primarily rest upon observation,{the subject of such observation being the very operations and processes of which we desire to determine the laws.“* (@boole1854investigation, para 1.4).

A problem he seeks to resolve through both the adoption and rejection of a dualism;

*” Now that truth is made manifest in all its generality by reflection upon a single instance of its application. And this is both an evidence that the particular principle or formula in question is founded upon some general law or laws of the mind, and an illustration of the doctrine that the perception of such general truths is not derived from an induction from many instances, but is involved in the clear apprehension of a single instance. In connexion with this truth is seen the not less important one that our knowledge of the laws upon which the science of the intellectual powers rests, whatever may be its extent or its deficiency, is not probable knowledge. For we not only see in the particular example the general truth, but we see it also as a certain truth,{a truth, our confidence in which will not continue to increase with increasing experience of its practical verifications. “*, (@boole1854investigation, para 1.5).

and

*" that they are individual objects of experience themselves; and that the propositions which relate to them are, on account of the imperfection of those objects, but partially true; lastly, that they are intellectual products formed by abstraction from the sensible perceptions of individual things, but so formed as to become, what the individual things never can be, subjects of science, i.e. subjects concerning which exact and general propositions may be affirmed"* (@boole1854investigation, para 22.5).

Here Boole argues for the duality of the cognitive objects being based on the induction from repeated observation and on the clear understanding of a single instance from which a “certain” truth (almost akin to a mathematical proof of a given law) will be derived. As the former only gives a probable or general truth, Boole’s focus is on later “certain” truths as the basis for the Science of Logic.

*” 5. But if the general truths of Logic are of such a nature that when presented to the mind they at once command assent, wherein consists the difficulty of constructing the Science of Logic? Not, it may be answered, in collecting the materials of knowledge, but in discriminating their nature, and determining their mutual place and relation.“*, (@boole1854investigation, para 1.5).

*” Let us define as fundamental those laws and principles from which all other general truths of science may be deduced, and into which they may all be again resolved. Shall we then err in regarding that as the true science of Logic which, laying down certain elementary laws, confirmed by the very testimony of the mind, permits us thence to deduce, by uniform processes, the entire chain of its secondary consequences, and furnishes, for its practical applications, methods of perfect generality? Let it be considered whether in any science, viewed either as a system of truth or as the foundation of a practical art, there can properly be any other test of the completeness and the fundamental character of its laws, than the completeness of its system of derived truths, and the generality of the methods which it serves to establish.“*, (@boole1854investigation, para 1.5).

Boole returns to this later;

*" It has been maintained, that propositions of the class referred to exist in the mind independently of experience, and that those conceptions which are the subjects of them are the imprints of eternal archetypes. With such archetypes, conceived, however, to possess a reality of which all the objects of sense are but a faint shadow or dim suggestion, Plato furnished his ideal world."* (@boole1854investigation, para 22.5).

Having established the primacy of abstractions as the objects of cognition, Boole turns to the central construct of his work;

*” It is designed, in the next place, to give expression in this treatise to the fundamental laws of reasoning in the symbolical language of a Calculus. Upon this head it will suffice to say, that those laws are such as to suggest this mode of expression, and to give to it a peculiar and exclusive fitness for the ends in view. There is not only a close analogy between the operations of the mind in general reasoning and its operations in the particular science of Algebra, but there is to a considerable extent an exact agreement in the laws by which the two classes of operations are conducted. Of course the laws must in both cases be determined independently; any formal agreement between them can only be established a posteriori by actual comparison“*, (@boole1854investigation, para1.6).

Before acknowledging that there must be some form of parity between the nature and actions of external objects and internal abstractions;

*” Logic is conversant with two kinds of relations,{relations among things, and relations among facts. But as facts are expressed by propositions, the latter species of relation may, at least for the purposes of Logic, be resolved into a relation among propositions. The assertion that the fact or event A is an invariable consequent of the fact or event B may, to this extent at least, be regarded as equivalent to the assertion, that the truth of the proposition arming the occurrence of the event B always implies the truth of the proposition arming the occurrence of the event A.“* (@boole1854investigation, para 1.7).

To give structure to his calculus Boole argues that;

*” Of the former kind of relations we have an example in the proposition “All men are mortal;" of the latter kind in the proposition “If the sun is totally eclipsed, the stars will become visible." The one expresses a relation between “men" and “mortal beings," the other between the elementary propositions “The sun is totally eclipsed;" “The stars will become visible." … Proceeding from this definition, we may then say that the premises of any logical argument express given relations among certain elements, and that the conclusion must express an implied relation among those elements, or among a part of them, i.e. a relation implied by or inferentially involved in the premises.  “* (@boole1854investigation, para 1.7).

A position which is analogous to his description of the relations between general truths based on repeated observations and their probable predictive power as discussed earlier.

**This assumption of the primacy of determinism based on abstract reasoning over probablmism based on observation as the basis for the universe will have far reaching effects, given the role of Boole's influence in information and computer science.**

Boole returns to the dualism between the abstract and the probabilistic objects of cognition.  As before, these entities remain distinct but exist in parallel so allowing his calculus to be applied to both;

*” The general doctrine and method of Logic above explained form also the basis of a theory and corresponding method of Probabilities. Accordingly, the development of such a theory and method, upon the above principles, will constitute a distinct object of the present treatise...Speaking technically, we must be able to express the event whose probability is sought, as a function of the events whose probabilities are given. Now this explicit determination belongs in all instances to the department of Logic. Probability, however, in its mathematical acceptation, admits of numerical measurement. Hence the subject of Probabilities belongs equally to the science of Number and to that of Logic.“* (@boole1854investigation, para 1.12)

Boole uses the term data with respect to understanding probability as follows;

*” Considered with reference to the data and the quaesitum, that type may be described as follows:*

*1st. The data are the probabilities of one or more given events, each probability being either that of the absolute fulfilment of the event to which it relates, or the probability of its fulfilment under given supposed conditions. *

*2ndly. The quaesitum, or object sought, is the probability of the fulfilment, absolutely or conditionally, of some other event differing in expression from those in the data, but more or less involving the same elements. As concerns the data, they are either causally given,- as when the probability of a particular throw of a die is deduced from a knowledge of the constitution of the piece - or they are derived from observation of repeated instances of the success or failure of events. In the latter case the probability of an event may be de ned as the limit toward which the ratio of the favourable to the whole number of observed cases approaches (the uniformity of nature being presupposed) as the observations are indefinitely continued.“*, (@boole1854investigation, para 1.13).

Suggesting that data is numbers driven by the laws of probability and related to the observed external world. As opposed to information which is the single abstract entity from which a proven fundamental law can rest. What is not clear from Boole’s work is the relationship between data and information, or more simply if the latter is not derived from sense data then how it is formed? If it is formed from sense data, then why is it exempt from the laws of probability that underpin Boole’s experienced universe?

Boole argues that external events are simple or compound;

*” Now one general problem, which the existing theory of Probabilities enables us to solve, is the following, viz.:-Given the probabilities of any simple events: required the probability of a given compound event, i.e. of an event compounded in a given manner out of the given simple events.“*, (@boole1854investigation, para 1.14).

Where compound events are often linked by either simple association or by “cause and effect”.

*” The problem can also be solved when the compound event, whose probability is required, is subjected to given conditions, i.e. to conditions dependent also in a given manner on the given simple events. Beside this general problem, there exist also particular problems of which the principle of solution is known. Various questions relating to causes and effects can be solved by known methods under the particular hypothesis that the causes are mutually exclusive, but apparently not otherwise.“* (@boole1854investigation, para 1.14).

Although he does not expand on the differences between a simple association and specific causation for the existence of compound events. Boole states that even events with an apparent cause to the observed effects are still only secondary objects as they can not support general truths like an abstract object.

*” All sciences consist of general truths, but of those truths some only are primary and fundamental, others are secondary and derived. The laws of elliptic motion, discovered by Kepler, are general truths in astronomy, but they are not its fundamental truths.“* (@boole1854investigation, para 1.5)

Given Boole’s claim that;

*” In the first place it is always possible, by the preliminary method of the Calculus of Logic, to express the event whose probability is sought as a logical function of the events whose probabilities are given.“*, (@boole1854investigation, para 1.15)

It would be tempting to suggest that Boole’s resolution of the duality between the abstract and the probabilistic is that both can be objects within his logical calculus. So although they have different concepts, and one has primacy over the other, both are still objects of the laws of thought.

Boole addresses the issue brought up subsequently by others as a source of criticism. The question  Boole posed was;

*” That Language is an instrument of human reason, and not merely a medium for the expression of thought, is a truth generally admitted. It is proposed in this chapter to inquire what it is that renders Language thus subservient to the most important of our intellectual faculties… In proceeding to these inquiries, it will not be necessary to enter into the discussion of that famous question of the schools, whether Language is to be regarded as an essential instrument of reasoning, or whether, on the other hand, it is possible for us to reason without its aid. “*(@boole1854investigation, para 2.1)

Following his dualism, Boole argued;

*” I suppose this question to be beside the design of the present treatise, for the following reason, viz., that it is the business of Science to investigate laws; and that, whether we regard signs as the representatives of things and of their relations, or as the representatives of the conceptions and operations of the human intellect, in studying the laws of signs, we are in effect studying the manifested laws of reasoning.”* (@boole1854investigation, para 2.1)

The consideration of the laws of signs a posteriori is the study of language, while from the above consideration of the law of the signs a priori is the laws of reasoning. Boole goes onto to define a sign as;

*” Definition - A sign is an arbitrary mark, having a  fixed interpretation, and susceptible of combination with other signs in subjection to fixed laws dependent upon their mutual interpretation. “*  (@boole1854investigation, para 2.2)

And to further clarify the relationship between the mark and its label;

*” In the first place, a sign is an arbitrary mark. It is clearly indifferent what particular word or token we associate with a given idea, provided that the association once made is permanent. The Romans expressed by the word “civitas" what we designate by the word “state." But both they and we might equally well have employed any other word to represent the same conception “*  (@boole1854investigation, para 2.3)

And 

*” In the second place, it is necessary that each sign should possess, within the limits of the same discourse or process of reasoning, a fixed interpretation. The necessity of this condition is obvious, and seems to be founded in the very nature of the subject. “* (@boole1854investigation, para 2.3)

Boole then, having defined to his satisfaction the link between language, a mark and the pure form of the objects internal mental representation, sets forth to define his algebra.

## Boole's logical algebra 
As stated earlier, @boole1854investigation seeks to bridge the gap between words and symbols, built on the preface “that Language is an instrument of human reason (p. 17)” although admitting that some have argued to reason without such an assumption.

The formulation rules of Boole’s algebra ((@boole1854investigation, para 2.4)) are;

1. A language consists of words which are signs or symbols, where a sign is admittedly arbitrary in its definition, within a given context and other associated signs.
2. Such an arbitrary definition may be contextual but within that context, it is also consistent within that context.
3. Such conceptual signs are represented by symbols as x, y…
4. +, -, * are signs of operation by which conceptual signs are combined or similar...
5. = is the sign for identity.
6. A combination of signs like “xy” is taken as the combination of x ^ y.
7. Given 6, then “xy = yx”.

Then Boole’s key mechanism can be developed;

\begin{equation}
 xy = x
\end{equation}

Boole goes onto to discuss how a symbol like **x** represents all men or the class of men. As will be discussed later this seen by some authors as Boole embracing and describing set theory, although Boole does not use this term and explicitly says he is using logic to consider the laws of reasoning.

*” Now, as it has been defined that a sign is an arbitrary mark, it is permissible to replace all signs of the species above described by letters. Let us then agree to represent the class of individuals to which a particular name or description is applicable, by a single letter, as x. If the name is “men," for instance, let x represent “all men," or the class “men." “*  (@boole1854investigation, para 2.6)

And further;

*” By a class is usually meant a collection of individuals, to each of which a particular name or description may be applied; but in this work the meaning of the term will be extended so as to include the case in which but a single individual exists, answering to the required name or description, as well as the cases denoted by the terms “nothing" and “universe," which as “classes" should be understood to comprise respectively “no beings," “all beings." Again, if an adjective, as “good," is employed as a term of description, let us represent by a letter, as y, all things to which the description “good" is applicable, i.e. “all good things," or the class "good things." Let it further be agreed, that by the combination xy shall be represented that class of things to which the names or descriptions represented by x and y are simultaneously applicable. Thus, if x alone stands for “white things," and y for “sheep," let xy stand for “white sheep;" and in like manner, if z stand for “horned things," and x and y retain their previous interpretations, let zxy represent “horned white sheep,“* (@boole1854investigation, para 2.6).

Then he consider the special the case where;

\begin{equation}
 xx = x
\end{equation}

Which is the case where x is of the same class as y. Hence;

\begin{equation}
 x^2 = x
\end{equation}

Which is only true if x = 0 or x = 1.


Boole’s proposed his law of duality;

\begin{equation}
x(1-x) = 0
\end{equation}

*" Hence x(1-x) will represent the class whose members are at once "men," and "not men," and the equation (1) thus express the principle, that a class whose members are at the same time men and not men does not exist. In other words, that it is impossible for the same individual to be at the same time a man and not a man.  Now let the meaning of the symbol x be extended from the representing of "men," to that of any class of beings characterized by the possession of any quality whatever; and the equation (1) will then express that it is impossible for a being to possess a quality and not to possess that quality at the same time...Thus it is a consequence of the fact that the fundamental equation of thought is of the second degree, that we perform the operation of analysis and classification, by division into pairs of opposites, or, as it is technically said, by dichotomy.'* (@boole1854investigation, para 3.15)

Where Boole means that an equation of the second degree is one where;

\begin{equation}
x^2 = x
\end{equation}

And a third order equation would be to the third power. 

### Boole's law of duality

Boole then goes onto to define the above as the law of duality;

*"The law of thought expressed by the equation (1) will, for reasons which are made apparent by the above discussion, be occasionally referred to as the "law of duality."* (@boole1854investigation, para 3.16)

Boole makes extensive use of this law of duality is the algebraic resolution of the propositions. 

*“We may arm, that in this peculiar system, the problem of elimination is resolvable under all circumstances alike. This is a consequence of that remarkable law of duality to which the symbols of Logic are subject. To the equations furnished by the premises given, there is added another equation or system of equations drawn from the fundamental laws of thought itself, and supplying the necessary means for the solution of the problem in question. Of the many consequences which flow from the law of duality, this is perhaps the most deserving of attention. "* (@boole1854investigation, para 7.2)

Thus for Boole, the dualism between external realism and internal cognitive objects is not in the sense of Cartesian dualism, rather it is the dualism of opposites. 

*“The famous comparison of the universe to a lyre or a bow, its “recurrent harmony" being the product of opposite states of tension, betrays the same origin. In the system of Pythagoras, which seems to have been a combination of dualism with other elements derived from the study of numbers, and of their relations, ten fundamental antitheses are recognised:  finite and infinite, even and odd, unity and multitude, right and left, male and female, rest and motion, straight and curved, light and darkness, good and evil, the square and the oblong ”*  (@boole1854investigation, para 12.7)

Leading to him adopting a position more akin to Plato’s Cave and the theory of forms (@cohen2016readings,  Republic VII para 514-517);

*“The unity of all real being, its identity with truth and goodness considered as to their essence; the illusion, the pro-found unreality, of all merely phenomenal existence; such were the views,|such the dispositions of thought, which it chiefly tended to foster. *” (@boole1854investigation, para 12.7)

And

*"Were this correspondence between the forms of thought and the actual constitution of Nature proved to exist, whatsoever connexion or relation it might be supposed to establish between the two systems, it would in no degree affect the question of their mutual independence."* (@boole1854investigation, para 12.8)

So that

*"We have no warrant for resolving these into mere forms of the understanding, though they unquestionably determine the present sphere of our knowledge. And, to speak more generally, there is no warrant for the extremely subjective tendency of much modern speculation. Whenever, in the view of the intellect, different hypotheses are equally consistent with an observed fact, the instinctive testimony of consciousness as to their relative value must be allowed to possess authority. ”* (@boole1854investigation, para 12.8)

For Boole then, the cognitive objectives that were manipulated by his algebra were Platonic rather than Cartesian in nature, where the cognitive object was the pure form on which the purity of mathematical thought could be applied.

Boole then clarifies that what is defined is a law of thought and not a law of things;

*”First, I would remark, that this law is a law of thought, and not, properly speaking, a law of things. Difference in the order of the qualities or attributes of an object, apart from all questions of causation, is a difference in conception merely. The law [xy = yx] expresses as a general truth, that the same thing may be conceived in different ways, and states the nature of that difference; and it does no more than this.  “*

And

*”As a law of thought, it is actually developed in a law of Language, the product and the instrument of thought “*

The third chapter is fascinating given its title *” Derivation Of The Laws Of The Symbols Of Logic From The Laws Of The Operations Of The Human Mind. “*  as it might be seen that Boole used the former to define the later but now wishes to beg the question.

Boole certainly agreed with Hume on (@Hume1751) the empiricist view that causation was nothing more than regularity of conjunction between cause and effect, built upon impressions of the external world. With such being key to science;

*”  The object of science, properly so called, is the knowledge of laws and relations. To be able to distinguish what is essential to this end, from what is only accidentally associated with it, is one of the most important conditions of scientific progress… Such questions, for instance, as the existence of a sustaining ground of phenomena, the reality of cause, the propriety of forms of speech implying that the successive states of things are connected by operations, and others of a like nature, may possess a deep interest and significance in relation to science, without being essentially scientific. It is indeed scarcely possible to express the conclusions of natural science without borrowing the language of these conceptions. “*  (@boole1854investigation, para 3.1)

He then attempts to define parallelism from his Humian position to the laws of reasoning. 

*” I would here assert, as affording us the only ground of confidence and stability amid so much of seeming and of real diversity, is the following, viz., that if the laws in question are really deduced from observation, they have a real existence as laws of the human mind, independently of any metaphysical theory which may seem to be involved in the mode of their statement. They contain an element of truth which no ulterior criticism upon the nature, or even upon the reality, of the mind's operations, can essentially affect. “* (@boole1854investigation, para 3.2)

For Boole, the laws of reasoning within the mind are not independent with our understanding of the external world.

*”  Moreover, as any statement of the laws of thought, founded upon actual observation, must thus contain scientific elements which are independent of metaphysical theories of the nature of the mind, the practical application of such elements to the construction of a system or method of reasoning must also be independent of metaphysical distinctions. For it is upon the scientific elements involved in the statement of the laws, that any practical application will rest, just as the practical conclusions of physical astronomy are independent of any theory of the cause of gravitation, but rest only on the knowledge of its phenomenal effects.“* (@boole1854investigation, para 3.2).

Although such a position would not be accepted now, for Boole it allowed him to argue that the process of cognition was independent of the neuroanatomical process which underpins cognition. 

*”  To those faculties or powers different names, as Attention, Simple Apprehension, Conception or Imagination, Abstraction, &c., have been given,|names which have not only furnished the titles of distinct divisions of the philosophy of the human mind, but passed into the common language of men. Whenever, then, occasion shall occur to use these terms, I shall do so without implying thereby that I accept the theory that the mind possesses such and such powers and faculties as distinct elements of its activity. Nor is it indeed necessary to inquire whether such powers of the understanding have a distinct existence or not. “* (@boole1854investigation, para 3.3).

Boole then proposed a framework for the consideration of the laws of reason.

Firstly that;

*” In every discourse, whether of the mind conversing with its own thoughts, or of the individual in his intercourse with others, there is an assumed or expressed limit within which the subjects of its operation are confined...Now, whatever may be the extent of the field within which all the objects of our discourse are found, that field may properly be termed the universe of discourse. “* (@boole1854investigation, para 3.4)

And

*” Furthermore, this universe of discourse is in the strictest sense the ultimate subject of the discourse...If that universe of discourse is the actual universe of things, which it always is when our words are taken in their real and literal sense, then by men we mean all men that exist; but if the universe of discourse is limited by any antecedent implied understanding, then it is of men under the limitation thus introduced that we speak.“*  (@boole1854investigation, para 3.5)

Boole then formulated the value and the significance of 0. 

*” To determine the logical value and significance of the symbols 0 and 1. The symbol 0, as used in Algebra, satisfies the following formal law, 0y = 0; or 0y = 0; whatever number y may represent...A little consideration will show that this condition is satisfied if the symbol 0 represent Nothing“* (@boole1854investigation, para 3.13).

And the significance of 1;

*” Secondly, The symbol 1 satisfies in the system of Number the following law, viz., 1 [times] y = y; or 1y = y; whatever number y may represent...A little consideration will here show that the class represented by 1 must be "the Universe," since this is the only class in which are found all the individuals that exist in any class. Hence the respective interpretations of the symbols 0 and 1 in the system of Logic are Nothing and Universe. “* (@boole1854investigation, para 3.13).

So while the Universe of Discourse has become fundamental to the study of Logic, that 0 is Nothing and 1 is the Universal has a similarly fundamental role in both the fields of logic and computer science. These are not arbitrary decisions, as so often is assumed. What will be seen later is that authors like Alonso Church did not automatically assume that 0 and 1 were numbers, rather that they were False and True. Modern computer languages often adopt a  messy state of “it depends” with some using a variable type such as a  Logical representing state of False or True but these are often represented internally as 0 or 1. Switching the data type from logical to an Integer allows numerous clever programmatic tricks to be performed on the altar of efficiency or expediency. 

### Propositions

Boole divided propositions into primary or concrete propositions or secondary and abstract propositions;

*” Proposition I. All logical propositions may be considered as belonging to one or the other of two great classes, to which the respective names of “Primary" or “Concrete Propositions," and “Secondary" or “Abstract Propositions," may be given.“* (@boole1854investigation, para 4.1).

He further clarifies this; 

*” Either it expresses a relation among things, or it expresses, or is equivalent to the expression of, a relation among propositions...The former class of propositions, relating to things, I call “Primary;" the latter class, relating to propositions, I call “Secondary.“*  (@boole1854investigation, para 4.1).


With a slight reference to Kant’s categorical or hypothetical propositions;

*"The distinction is in practice nearly but not quite co-extensive with the common logical distinction of propositions as categorical or hypothetical.“* (@boole1854investigation, para 4.1).

And Boole was happy for a secondary proposition to imply causation if regular in its conjunction. Likewise;

*“ Every primary proposition may thus give rise to a secondary proposition, viz., to that secondary proposition which asserts its truth, or declares its falsehood.“* (@boole1854investigation, para 4.2).

But at the end of the day;

*” In the expression both of primary and of secondary propositions, the same symbols, subject, as it will appear, to the same laws, will be employed in this work. The difference between the two cases is a difference not of form but of interpretation.“* (@boole1854investigation, para 4.3)


Boole further clarifies his Platonic dualism on the nature of reality with respect to Primary propositions, namely the abstract nature of things.

*” I would then remark, that the principle in question may be considered as resting upon a general law of the mind, the knowledge of which is not given to us a priori, i.e. antecedently to experience, but is derived, like the knowledge of the other laws of the mind, from the clear manifestation of the general principle in the particular instance...No accumulation of instances can properly add weight to such evidence. It may furnish us with clearer conceptions of that common element of truth upon which the application of the principle depends, and so prepare the way for its reception. It may, where the immediate force of the evidence is not felt, serve as a verification,  a posteriori, of the practical validity of the principle in question.  “*(@boole1854investigation, para 5.5)

And again;

*”I answer, that the mind assumes the existence of a universe not a priori as a fact independent of experience, but either a posteriori as a deduction from experience, or hypothetically as a foundation of the possibility of assertive reasoning. “* (@boole1854investigation, para 6.6)

In contrast to secondary propositions, which he now refines the definition to be;

*” The doctrine has already been established in Chap. IV., that every logical proposition may be referred to one or the other of two great classes, viz., Primary Propositions and Secondary Propositions. The former of these classes has been discussed in the preceding chapters of this work, and we are now led to the consideration of Secondary Propositions, i.e. of Propositions concerning, or relating to, other propositions regarded as true or false. “* (@boole1854investigation, para 11.1).

And

*” The relations of things we express by primary propositions. But we are able to make Propositions themselves also the subject of thought, and to express our judgments concerning them. The expression of any such judgment constitutes a secondary proposition.“* (@boole1854investigation, para 11.2).

But also such conditional propositions so that;

*” Secondary propositions also include all judgments by which we express a relation or dependence among propositions...It may involve both the disjunctive element expressed by either, or, and the conditional element expressed by if; in addition to which, the connected propositions may themselves be of a compound character. “* (@boole1854investigation, para 11.2).

Although Boole did acknowledge that for his algebra for both would be similar;

*” The investigation upon which we are entering will, in its general order and progress, resemble that which we have already conducted. The two inquiries differ as to the subjects of thought which they recognise, not as to the formal and scientific laws which they reveal, or the methods or processes which are founded upon those laws.“* (@boole1854investigation, para 11.1).

And 

*” The discussion of the theory of Secondary Propositions is in the next place interesting, from the close and remarkable analogy which it bears with the theory of Primary Propositions. It will appear, that the formal laws to which the operations of the mind are subject, are identical in expression in both cases. The mathematical processes which are founded on those laws are, therefore, identical also.“* (@boole1854investigation, para 11.4).

Where they differ for Boole was.

*” But in treating of secondary propositions, we  find ourselves concerned with another class both of subjects and relations...the relations among these subject propositions are relations of coexistent truth or falsehood, not of substantive equivalence.“* (@boole1854investigation, para 11.5).

And with the element of time as well;

*” The language of common life sanctions this view of the essential connexion of secondary propositions with the notion of time...There are indeed propositions, the truth of which is not thus limited to particular periods or conjunctures; propositions which are true throughout all time, and have received the appellation of ‘eternal truths’. “* (@boole1854investigation, para 11.5).

Although time is often dropped from consideration in many instances;

*” We may here call attention again to the remark, that although the idea of time appears to be an essential element in the theory of the interpretation of secondary propositions, it may practically be neglected as soon as the laws of expression and of interpretation are definitely established.“* (@boole1854investigation, para 11.15).

Once more Boole uses that is a secondary proposition (X) is true then (X = 1) and likewise (X=0) if the proposition (X) is false  (@boole1854investigation, para 11.11).

In summary, Boole settles on the distinction between primary and secondary propositions as;

*” We might undoubtedly, have established the theory of Primary Propositions upon the simple notion of space, in the same way as that of secondary propositions has been established upon the notion of time.“* (@boole1854investigation, para 11.16).

Although he immediately backs away from the former;

*” I conceive, therefore, that the idea of space is not essential to the development of a theory of primary propositions,“*  (@boole1854investigation, para 11.16).

And now having embraced time, while previously having rejected time as key to secondary propositions, Boole restates his concerns;

*” I was led to interpret the symbol 1 in secondary propositions as the universe of “cases" or “conjunctures of circumstances;" but this view involves the necessity of a definition of what is meant by a “case," or “conjuncture of circumstances;" and it is certain, that whatever is involved in the term beyond the notion of time is alien to the objects, and restrictive of the processes, of formal Logic.“* (@boole1854investigation, para 11.16).

## Boole's statistics

Boole built upon Possoin’s definition of probability as;

*” The probability of an event is the reason we have to believe that it has taken place, or that it will take place“*

Or

*” The measure of the probability of an event is the ratio of the number of cases favourable to that event, to the total number of cases favourable or contrary, and all equally possible“*

To give his working definition of probability as;

*” it follows that the word probability, in its mathematical acceptation, has reference to the state of our knowledge of the circumstances under which an event may happen or fail.“* (@boole1854investigation, para 16.2).

But believes that all probability is based on only partial knowledge because;

*” Probability is expectation founded upon partial knowledge. A perfect acquaintance with all the circumstances affecting the occurrence of an event would change expectation into certainty, and leave neither room nor demand for a theory of probabilities. “* (@boole1854investigation, para 16.2).

And starts to build his hypothesis;

*” The rules which we employ in life-assurance, and in the other statistical applications of the theory of probabilities, are altogether independent of the mental phenomena of expectation. They are founded upon the assumption that the future will bear a resemblance to the past; that under the same circumstances the same event will tend to recur with a de nite numerical frequency; not upon any attempt to submit to calculation the strength of human hopes and fears. “* (@boole1854investigation, para 16.3).

That probability theory considers the external imperfect world, Plato’s shadows from the Cave as opposed to their pure mental forms. Before bending his conceptualization back from the probability of occurrence to the probability of an event is true.

*” this form consists in substituting for events the propositions which assert that those events have occurred, or will occur; and viewing the element of numerical probability as having reference to the truth of those propositions, not to the occurrence of the events concerning which they make assertion.“* (@boole1854investigation, para 16.6).

Which by modern sensibilities are not two different positions but each is a simple restatement of the other.

Boole then states the beginning of probability theory, in a style that is consistent with his calculus. This enables him to use his algebra to solve problems of external reality that is analogous to how he resolves laws of internal reality. 

*” Now in the science of pure Logic, which, as such, is conversant only with truth and with falsehood, the above disjunctive and conditional propositions are equivalent. They are true and they are false together. It is seen, however, from the above investigation, that when the disjunctive proposition has a probability p, the conditional proposition has a different and partly indefinite probability cp/1-p+cp . Nevertheless these expressions are such, that when either of them becomes 1 or 0, the other assumes the same value. The results are, therefore, perfectly consistent, and the logical transformation serves to verify the formula deduced from the theory of probabilities. “*  (@boole1854investigation, para 18.8).

While missing concept and their importance of the sample population, other techniques “bootstrapping” are described (@boole1854investigation, para 18.4).

## Boole's causation

Boole focuses on the concept of Cause and Effect;

*” So to apprehend in all particular instances the relation of cause and effect, as to connect the two extremes in thought according to the order in which they are connected in nature (for the modus operandi is, and must ever be, unknown to us), is the final object of science….There is a sphere of thought which comprehends things only as coexistent parts of a universe; but there is also a sphere of thought (Chap. xi.) in which they are apprehended as links of an unbroken, and, to human appearance, an endless chain - as having their place in an order connecting them both with that which has gone before, and with that which shall follow after. In the contemplation of such a series, it is impossible not to feel the pre-eminence which is due, above all other relations, to the relation of cause and effect. “* (@boole1854investigation, para 20.1).


*” From the probabilities of causes assigned a priori, or given by experience, and their respective probabilities of association with an effect contemplated, it may be required to determine the probability of that effect“* (@boole1854investigation, para 20.1).

But having established the challenges to his approach with respect to Cause and Effect, Boole then states;

*” I would remark, that although these examples are designed chiefly as illustrations of a method, no regard has been paid to the question of ease or convenience in the application of that method. On the contrary, they have been devised, with whatever success, as types of the class of problems which might be expected to arise from the study of the relation of cause and effect in the more complex of its actual and visible manifestations.“* (@boole1854investigation, para 20.1).

But continues to largely adopt Hume’s regularity theory of causation and considers this from the perspective of the probability that an effect follows the cause. In the examples Boole gave knowledge as to the cause was known a priori. He argues however even when this is not known, then a strong association is inevitable. Boole gives the example of the planets being aligned on the ecliptic plane, which allows authors at the time to conclude there must be a very high probability of a common cause even if it is unknown (then) (@boole1854investigation, para 20.19). Boole makes the sensible caution that for a probability or observation-based theory of causation, theory can never escape the data on which it is based.

Interestingly Boole conjoins his internal and external realities, arguing the whole is greater than the sum of the parts;

*”  One of the first conclusions to which it leads is that of the necessary insufficiency of any data that experience alone can furnish, for the accomplishment of the most important object of the inquiry. But in setting clearly before us the necessity of hypotheses as supplementary to the data of experience, and in enabling us to deduce with rigour the consequences of any hypothesis which may be assumed,“* (@boole1854investigation, para 20.19). 

\newpage